//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.API.T24ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inquery.bidc.com/", ConfigurationName="T24ServiceReference.InqueryWebService")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService'
    public interface InqueryWebService {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService'
        
        // CODEGEN: Generating message contract since element name inputXML from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://inquery.bidc.com/InqueryWebService/InqueryServiceRequest", ReplyAction="http://inquery.bidc.com/InqueryWebService/InqueryServiceResponse")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.InqueryService(InqueryServiceRequest)'
        InvoiceServer.API.T24ServiceReference.InqueryServiceResponse InqueryService(InvoiceServer.API.T24ServiceReference.InqueryServiceRequest request);
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.InqueryService(InqueryServiceRequest)'
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inquery.bidc.com/InqueryWebService/InqueryServiceRequest", ReplyAction="http://inquery.bidc.com/InqueryWebService/InqueryServiceResponse")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.InqueryServiceAsync(InqueryServiceRequest)'
        System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.InqueryServiceResponse> InqueryServiceAsync(InvoiceServer.API.T24ServiceReference.InqueryServiceRequest request);
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.InqueryServiceAsync(InqueryServiceRequest)'
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://inquery.bidc.com/InqueryWebService/helloRequest", ReplyAction="http://inquery.bidc.com/InqueryWebService/helloResponse")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.hello(helloRequest)'
        InvoiceServer.API.T24ServiceReference.helloResponse hello(InvoiceServer.API.T24ServiceReference.helloRequest request);
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.hello(helloRequest)'
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inquery.bidc.com/InqueryWebService/helloRequest", ReplyAction="http://inquery.bidc.com/InqueryWebService/helloResponse")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.helloAsync(helloRequest)'
        System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.helloResponse> helloAsync(InvoiceServer.API.T24ServiceReference.helloRequest request);
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebService.helloAsync(helloRequest)'
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest'
    public partial class InqueryServiceRequest {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest'
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InqueryService", Namespace="http://inquery.bidc.com/", Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.Body'
        public InvoiceServer.API.T24ServiceReference.InqueryServiceRequestBody Body;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.Body'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.InqueryServiceRequest()'
        public InqueryServiceRequest() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.InqueryServiceRequest()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.InqueryServiceRequest(InqueryServiceRequestBody)'
        public InqueryServiceRequest(InvoiceServer.API.T24ServiceReference.InqueryServiceRequestBody Body) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequest.InqueryServiceRequest(InqueryServiceRequestBody)'
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody'
    public partial class InqueryServiceRequestBody {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody'
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.inputXML'
        public string inputXML;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.inputXML'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.InqueryServiceRequestBody()'
        public InqueryServiceRequestBody() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.InqueryServiceRequestBody()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.InqueryServiceRequestBody(string)'
        public InqueryServiceRequestBody(string inputXML) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceRequestBody.InqueryServiceRequestBody(string)'
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse'
    public partial class InqueryServiceResponse {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse'
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InqueryServiceResponse", Namespace="http://inquery.bidc.com/", Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.Body'
        public InvoiceServer.API.T24ServiceReference.InqueryServiceResponseBody Body;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.Body'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.InqueryServiceResponse()'
        public InqueryServiceResponse() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.InqueryServiceResponse()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.InqueryServiceResponse(InqueryServiceResponseBody)'
        public InqueryServiceResponse(InvoiceServer.API.T24ServiceReference.InqueryServiceResponseBody Body) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponse.InqueryServiceResponse(InqueryServiceResponseBody)'
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody'
    public partial class InqueryServiceResponseBody {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody'
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.@return'
        public string @return;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.@return'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.InqueryServiceResponseBody()'
        public InqueryServiceResponseBody() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.InqueryServiceResponseBody()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.InqueryServiceResponseBody(string)'
        public InqueryServiceResponseBody(string @return) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryServiceResponseBody.InqueryServiceResponseBody(string)'
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequest'
    public partial class helloRequest {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequest'
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://inquery.bidc.com/", Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.Body'
        public InvoiceServer.API.T24ServiceReference.helloRequestBody Body;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.Body'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.helloRequest()'
        public helloRequest() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.helloRequest()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.helloRequest(helloRequestBody)'
        public helloRequest(InvoiceServer.API.T24ServiceReference.helloRequestBody Body) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequest.helloRequest(helloRequestBody)'
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody'
    public partial class helloRequestBody {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody'
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.name'
        public string name;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.name'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.helloRequestBody()'
        public helloRequestBody() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.helloRequestBody()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.helloRequestBody(string)'
        public helloRequestBody(string name) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloRequestBody.helloRequestBody(string)'
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponse'
    public partial class helloResponse {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponse'
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://inquery.bidc.com/", Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.Body'
        public InvoiceServer.API.T24ServiceReference.helloResponseBody Body;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.Body'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.helloResponse()'
        public helloResponse() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.helloResponse()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.helloResponse(helloResponseBody)'
        public helloResponse(InvoiceServer.API.T24ServiceReference.helloResponseBody Body) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponse.helloResponse(helloResponseBody)'
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody'
    public partial class helloResponseBody {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody'
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.@return'
        public string @return;
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.@return'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.helloResponseBody()'
        public helloResponseBody() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.helloResponseBody()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.helloResponseBody(string)'
        public helloResponseBody(string @return) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'helloResponseBody.helloResponseBody(string)'
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceChannel'
    public interface InqueryWebServiceChannel : InvoiceServer.API.T24ServiceReference.InqueryWebService, System.ServiceModel.IClientChannel {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceChannel'
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient'
    public partial class InqueryWebServiceClient : System.ServiceModel.ClientBase<InvoiceServer.API.T24ServiceReference.InqueryWebService>, InvoiceServer.API.T24ServiceReference.InqueryWebService {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient'
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient()'
        public InqueryWebServiceClient() {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient()'
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string)'
        public InqueryWebServiceClient(string endpointConfigurationName) : 
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string)'
                base(endpointConfigurationName) {
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string, string)'
        public InqueryWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string, string)'
                base(endpointConfigurationName, remoteAddress) {
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string, EndpointAddress)'
        public InqueryWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(string, EndpointAddress)'
                base(endpointConfigurationName, remoteAddress) {
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(Binding, EndpointAddress)'
        public InqueryWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryWebServiceClient(Binding, EndpointAddress)'
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceServer.API.T24ServiceReference.InqueryServiceResponse InvoiceServer.API.T24ServiceReference.InqueryWebService.InqueryService(InvoiceServer.API.T24ServiceReference.InqueryServiceRequest request) {
            return base.Channel.InqueryService(request);
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryService(string)'
        public string InqueryService(string inputXML) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryService(string)'
            InvoiceServer.API.T24ServiceReference.InqueryServiceRequest inValue = new InvoiceServer.API.T24ServiceReference.InqueryServiceRequest();
            inValue.Body = new InvoiceServer.API.T24ServiceReference.InqueryServiceRequestBody();
            inValue.Body.inputXML = inputXML;
            InvoiceServer.API.T24ServiceReference.InqueryServiceResponse retVal = ((InvoiceServer.API.T24ServiceReference.InqueryWebService)(this)).InqueryService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.InqueryServiceResponse> InvoiceServer.API.T24ServiceReference.InqueryWebService.InqueryServiceAsync(InvoiceServer.API.T24ServiceReference.InqueryServiceRequest request) {
            return base.Channel.InqueryServiceAsync(request);
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryServiceAsync(string)'
        public System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.InqueryServiceResponse> InqueryServiceAsync(string inputXML) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.InqueryServiceAsync(string)'
            InvoiceServer.API.T24ServiceReference.InqueryServiceRequest inValue = new InvoiceServer.API.T24ServiceReference.InqueryServiceRequest();
            inValue.Body = new InvoiceServer.API.T24ServiceReference.InqueryServiceRequestBody();
            inValue.Body.inputXML = inputXML;
            return ((InvoiceServer.API.T24ServiceReference.InqueryWebService)(this)).InqueryServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceServer.API.T24ServiceReference.helloResponse InvoiceServer.API.T24ServiceReference.InqueryWebService.hello(InvoiceServer.API.T24ServiceReference.helloRequest request) {
            return base.Channel.hello(request);
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.hello(string)'
        public string hello(string name) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.hello(string)'
            InvoiceServer.API.T24ServiceReference.helloRequest inValue = new InvoiceServer.API.T24ServiceReference.helloRequest();
            inValue.Body = new InvoiceServer.API.T24ServiceReference.helloRequestBody();
            inValue.Body.name = name;
            InvoiceServer.API.T24ServiceReference.helloResponse retVal = ((InvoiceServer.API.T24ServiceReference.InqueryWebService)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.helloResponse> InvoiceServer.API.T24ServiceReference.InqueryWebService.helloAsync(InvoiceServer.API.T24ServiceReference.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.helloAsync(string)'
        public System.Threading.Tasks.Task<InvoiceServer.API.T24ServiceReference.helloResponse> helloAsync(string name) {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'InqueryWebServiceClient.helloAsync(string)'
            InvoiceServer.API.T24ServiceReference.helloRequest inValue = new InvoiceServer.API.T24ServiceReference.helloRequest();
            inValue.Body = new InvoiceServer.API.T24ServiceReference.helloRequestBody();
            inValue.Body.name = name;
            return ((InvoiceServer.API.T24ServiceReference.InqueryWebService)(this)).helloAsync(inValue);
        }
    }
}
