//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNOUNCEMENT
    {
        public long ID { get; set; }
        public string TITLE { get; set; }
        public string LEGALGROUNDS { get; set; }
        public System.DateTime ANNOUNCEMENTDATE { get; set; }
        public long COMPANYID { get; set; }
        public string COMPANYNAME { get; set; }
        public string COMPANYADDRESS { get; set; }
        public string COMPANYTEL { get; set; }
        public string COMPANYTAXCODE { get; set; }
        public string COMPANYREPRESENTATIVE { get; set; }
        public string COMPANYPOSITION { get; set; }
        public string CLIENTNAME { get; set; }
        public string CLIENTADDRESS { get; set; }
        public string CLIENTTEL { get; set; }
        public string CLIENTTAXCODE { get; set; }
        public string CLIENTREPRESENTATIVE { get; set; }
        public string CLIENTPOSITION { get; set; }
        public long INVOICEID { get; set; }
        public long REGISTERTEMPLATEID { get; set; }
        public string DENOMINATOR { get; set; }
        public string SYMBOL { get; set; }
        public string INVOICENO { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string SERVICENAME { get; set; }
        public string REASION { get; set; }
        public string BEFORECONTAIN { get; set; }
        public string CHANGECONTAIN { get; set; }
        public int ANNOUNCEMENTTYPE { get; set; }
        public int ANNOUNCEMENTSTATUS { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public long UPDATEDBY { get; set; }
        public System.DateTime UPDATEDDATE { get; set; }
        public Nullable<long> APPROVEDBY { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
        public Nullable<long> PROCESSBY { get; set; }
        public Nullable<System.DateTime> PROCESSDATE { get; set; }
        public Nullable<bool> COMPANYSIGN { get; set; }
        public Nullable<bool> CLIENTSIGN { get; set; }
        public Nullable<System.DateTime> COMPANYSIGNDATE { get; set; }
        public Nullable<System.DateTime> CLIENTSIGNDATE { get; set; }
        public string MINUTESNO { get; set; }
    }
}
