//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTONUMBERSETTING
    {
        public string TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public bool ENABLED1 { get; set; }
        public bool ENABLED2 { get; set; }
        public bool ENABLED3 { get; set; }
        public Nullable<byte> S1TYPE { get; set; }
        public Nullable<byte> S2TYPE { get; set; }
        public Nullable<byte> S3TYPE { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public bool SEPARATED { get; set; }
        public string SEPARATORS { get; set; }
        public Nullable<byte> OUTPUTLENGTH { get; set; }
        public Nullable<byte> OUTPUTORDERS { get; set; }
        public Nullable<int> ORDERBY { get; set; }
        public bool ACTIVED { get; set; }
        public long CREATEUSERSID { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public long UPDATEUSERSID { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public Nullable<bool> ENABLED4 { get; set; }
        public Nullable<byte> S4TYPE { get; set; }
        public string S4 { get; set; }
    }
}
