//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCELLINGINVOICE
    {
        public long ID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<long> INVOICEID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CANCELLEDDATE { get; set; }
        public Nullable<long> CANCELBY { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
    }
}
