//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.INVOICEs = new HashSet<INVOICE>();
        }
    
        public long ID { get; set; }
        public string CUSTOMERID { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string TAXCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> TYPESENDINVOICE { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string DELEGATE { get; set; }
        public string PERSONCONTACT { get; set; }
        public string BANKACCOUNT { get; set; }
        public string ACCOUNTHOLDER { get; set; }
        public string BANKNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CUSTOMERTYPE { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<bool> ISORG { get; set; }
        public Nullable<bool> SENDINVOICEBYMONTH { get; set; }
        public Nullable<int> DATESENDINVOICE { get; set; }
        public Nullable<bool> TAXINCENTIVES { get; set; }
        public Nullable<bool> USETOTALINVOICE { get; set; }
        public Nullable<bool> USEREGISTEREMAIL { get; set; }
        public string RECEIVEDINVOICEEMAIL { get; set; }
        public string IDENTITY { get; set; }
        public string TRX_BRANCH_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
    }
}
