//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGEMAILSERVER
    {
        public long ID { get; set; }
        public Nullable<bool> AUTOSENDEMAIL { get; set; }
        public Nullable<bool> METHODSENDSSL { get; set; }
        public string SMTPSERVER { get; set; }
        public Nullable<int> PORT { get; set; }
        public string EMAILSERVER { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> SECURESOCKETOPTIONS { get; set; }
        public string USERNAME { get; set; }
    }
}
