//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILACTIVEFILEATTACH
    {
        public long ID { get; set; }
        public Nullable<long> EMAILACTIVEID { get; set; }
        public string FULLPATHFILEATTACH { get; set; }
        public string FILENAME { get; set; }
    
        public virtual EMAILACTIVE EMAILACTIVE { get; set; }
    }
}
