//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILACTIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMAILACTIVE()
        {
            this.EMAILACTIVEFILEATTACHes = new HashSet<EMAILACTIVEFILEATTACH>();
        }
    
        public long ID { get; set; }
        public string TITLE { get; set; }
        public string EMAILTO { get; set; }
        public Nullable<int> SENDSTATUS { get; set; }
        public string CONTENTEMAIL { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> SENDTEDDATE { get; set; }
        public Nullable<int> TYPEEMAIL { get; set; }
        public Nullable<long> COMPANYID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILACTIVEFILEATTACH> EMAILACTIVEFILEATTACHes { get; set; }
    }
}
