//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLDINVOICEDETAIL
    {
        public long ID { get; set; }
        public long HOLDINVOICEID { get; set; }
        public string INVOICENO { get; set; }
        public int INVOICESTATUS { get; set; }
    
        public virtual HOLDINVOICE HOLDINVOICE { get; set; }
    }
}
