//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLDINVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOLDINVOICE()
        {
            this.HOLDINVOICEDETAILs = new HashSet<HOLDINVOICEDETAIL>();
        }
    
        public long ID { get; set; }
        public long COMPANYID { get; set; }
        public long REGISTERTEMPLATEID { get; set; }
        public string CODE { get; set; }
        public string SYMBOL { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string NUMBERFROM { get; set; }
        public string NUMBERTO { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    
        public virtual REGISTERTEMPLATE REGISTERTEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDINVOICEDETAIL> HOLDINVOICEDETAILs { get; set; }
    }
}
