//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_LOG
    {
        public long ID { get; set; }
        public string FILEPATH { get; set; }
        public string FILENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DATE { get; set; }
        public Nullable<bool> ISSUCCESS { get; set; }
    }
}
