//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICEDECLARATIONRELEASEREGISTERTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICEDECLARATIONRELEASEREGISTERTYPE()
        {
            this.INVOICEDECLARATIONRELEASEs = new HashSet<INVOICEDECLARATIONRELEASE>();
        }
    
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICEDECLARATIONRELEASE> INVOICEDECLARATIONRELEASEs { get; set; }
    }
}
