//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICETEMPLATESAMPLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICETEMPLATESAMPLE()
        {
            this.INVOICESAMPLEs = new HashSet<INVOICESAMPLE>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string URLFILE { get; set; }
        public string IMAGETEMPLATE { get; set; }
        public string DETAILINVOICE { get; set; }
        public Nullable<int> NUMBERRECORD { get; set; }
        public bool ISSHOWORDER { get; set; }
        public Nullable<int> ORDERS { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public string PAGESIZE { get; set; }
        public string PAGEORIENTATION { get; set; }
        public decimal LOCATIONSIGNLEFT { get; set; }
        public decimal LOCATIONSIGNBUTTON { get; set; }
        public Nullable<int> NUMBERCHARACTERINLINE { get; set; }
        public Nullable<decimal> LOCATIONSIGNRIGHT { get; set; }
        public string FOOTERINVOICE { get; set; }
        public string HEADERINVOICE { get; set; }
        public Nullable<bool> ISMULTITAX { get; set; }
        public Nullable<bool> ISDISCOUNT { get; set; }
        public int NUMBERLINEOFPAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICESAMPLE> INVOICESAMPLEs { get; set; }
    }
}
