//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICESAMPLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICESAMPLE()
        {
            this.REGISTERTEMPLATES = new HashSet<REGISTERTEMPLATE>();
        }
    
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string NAMEREPORT { get; set; }
        public Nullable<bool> ISMULTITAX { get; set; }
        public Nullable<bool> ISDISCOUNT { get; set; }
        public Nullable<long> INVOICETYPEID { get; set; }
        public string DENOMINATOR { get; set; }
        public string FILENAME { get; set; }
        public string NOTE { get; set; }
        public string TEMPLATEURL { get; set; }
        public Nullable<long> INVOICETEMPLATESAMPLEID { get; set; }
    
        public virtual INVOICETEMPLATESAMPLE INVOICETEMPLATESAMPLE { get; set; }
        public virtual INVOICETYPE INVOICETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTERTEMPLATE> REGISTERTEMPLATES { get; set; }
    }
}
