//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICEDECLARATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICEDECLARATION()
        {
            this.SYMBOLs = new HashSet<SYMBOL>();
            this.INVOICEDECLARATIONRELEASEs = new HashSet<INVOICEDECLARATIONRELEASE>();
        }
    
        public long ID { get; set; }
        public string COMPANYNAME { get; set; }
        public string COMPANYTAXCODE { get; set; }
        public long TAXDEPARTMENTID { get; set; }
        public string CUSTNAME { get; set; }
        public string CUSTADDRESS { get; set; }
        public string CUSTEMAIL { get; set; }
        public string CUSTPHONE { get; set; }
        public long CITYID { get; set; }
        public System.DateTime DECLARATIONDATE { get; set; }
        public Nullable<int> DECLARATIONTYPE { get; set; }
        public Nullable<int> HTHDON { get; set; }
        public Nullable<int> HTGDLHDDT { get; set; }
        public Nullable<int> PTHUC { get; set; }
        public Nullable<int> LHDSDUNG { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string SYMBOL { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string MESSAGECODE { get; set; }
        public Nullable<long> REGISTERTEMPLATEID { get; set; }
    
        public virtual REGISTERTEMPLATE REGISTERTEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYMBOL> SYMBOLs { get; set; }
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICEDECLARATIONRELEASE> INVOICEDECLARATIONRELEASEs { get; set; }
    }
}
