//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_HIST
    {
        public long ID { get; set; }
        public Nullable<long> PARENTID { get; set; }
        public Nullable<long> CLIENTID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<long> REGISTERTEMPLATEID { get; set; }
        public string SYMBOL { get; set; }
        public string NO { get; set; }
        public string NUMBERACCOUT { get; set; }
        public string CODE { get; set; }
        public Nullable<long> TYPEPAYMENT { get; set; }
        public Nullable<int> INVOICESTATUS { get; set; }
        public Nullable<int> INVOICETYPE { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> TOTALTAX { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> SUM { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<long> DELETEDBY { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
        public Nullable<long> APPROVEDBY { get; set; }
        public Nullable<bool> RELEASED { get; set; }
        public Nullable<System.DateTime> RELEASEDDATE { get; set; }
        public Nullable<decimal> INVOICENO { get; set; }
        public string CUSTOMERNAME { get; set; }
        public Nullable<decimal> TOTALDISCOUNT { get; set; }
        public Nullable<bool> CLIENTSIGN { get; set; }
        public Nullable<decimal> TOTALDISCOUNTTAX { get; set; }
        public Nullable<int> ISDISCOUNT { get; set; }
        public string ORIGINNO { get; set; }
        public string PARENTCODE { get; set; }
        public string PARENTSYMBOL { get; set; }
        public string FILERECEIPT { get; set; }
        public Nullable<System.DateTime> CLIENTSIGNDATE { get; set; }
        public Nullable<long> CURRENCYID { get; set; }
        public Nullable<bool> SENDMAILSTATUS { get; set; }
        public Nullable<decimal> CURRENCYEXCHANGERATE { get; set; }
        public string PERSONCONTACT { get; set; }
        public string CUSTOMERTAXCODE { get; set; }
        public string CUSTOMERADDRESS { get; set; }
        public string CUSTOMERBANKACC { get; set; }
        public string COMPANYNAME { get; set; }
        public string COMPANYADDRESS { get; set; }
        public string COMPANYTAXCODE { get; set; }
        public string REFNUMBER { get; set; }
        public string REFINVOICENO { get; set; }
        public string TELLER { get; set; }
        public Nullable<bool> CREATEDFILE { get; set; }
        public Nullable<int> HTHDON { get; set; }
        public Nullable<long> DECLAREID { get; set; }
        public string MESSAGECODE { get; set; }
        public string REPORT_CLASS { get; set; }
        public string FEE_BEN_OUR { get; set; }
        public string VAT_INVOICE_TYPE { get; set; }
        public string VAT_RATE { get; set; }
        public string CIF_NO { get; set; }
        public string REFUND_TYPE { get; set; }
        public string YEARMONTH { get; set; }
        public string VERIFICATIONCODE { get; set; }
        public string TRX_BRANCH_NO { get; set; }
        public Nullable<long> IMPORTTYPE { get; set; }
        public Nullable<decimal> BTHERRORSTATUS { get; set; }
        public string BTHERROR { get; set; }
        public Nullable<bool> CONVERTED { get; set; }
        public Nullable<System.DateTime> CONVERTDATE { get; set; }
        public string CONVERTER { get; set; }
        public Nullable<System.DateTime> HIST_DATE { get; set; }
    }
}
