//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICERELEASESDETAIL
    {
        public long ID { get; set; }
        public Nullable<long> INVOICECONCLUDEID { get; set; }
        public Nullable<long> REGISTERTEMPLATESID { get; set; }
        public Nullable<long> INVOICESAMPLEID { get; set; }
        public string SYMBOL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public string INVOICETYPENAME { get; set; }
        public string REGISTERTEMPLATECODE { get; set; }
        public string INVOICESAMPLENAME { get; set; }
    
        public virtual INVOICERELEAS INVOICERELEAS { get; set; }
        public virtual REGISTERTEMPLATE REGISTERTEMPLATE { get; set; }
    }
}
