//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICEGIFT
    {
        public long ID { get; set; }
        public long INVOICEID { get; set; }
        public long COMPANYID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string REFNO { get; set; }
        public string SEQUENCE { get; set; }
        public string PERIODTAX { get; set; }
        public string GIFTNAME { get; set; }
        public string REMARK { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> PRETAXAMOUNT { get; set; }
        public string TAX { get; set; }
        public Nullable<decimal> AMOUNTTAX { get; set; }
        public string TYPEGIFT { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
    }
}
