//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICERELEAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICERELEAS()
        {
            this.INVOICERELEASESDETAILs = new HashSet<INVOICERELEASESDETAIL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string CODE { get; set; }
        public string MANAGER { get; set; }
        public string PERSIONSUGGEST { get; set; }
        public string NOTE { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public Nullable<System.DateTime> RELEASEDDATE { get; set; }
        public string RECIPIENTS { get; set; }
        public Nullable<long> CITYID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public string NOTE4 { get; set; }
        public string COMPANYNAME { get; set; }
        public string CITYNAME { get; set; }
        public string TAXCODE { get; set; }
    
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICERELEASESDETAIL> INVOICERELEASESDETAILs { get; set; }
    }
}
