//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGINUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGINUSER()
        {
            this.RELEASEANNOUNCEMENTs = new HashSet<RELEASEANNOUNCEMENT>();
            this.RELEASEINVOICEs = new HashSet<RELEASEINVOICE>();
            this.ROLEs = new HashSet<ROLE>();
        }
    
        public long USERSID { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> USERLEVELSID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string LANGUAGE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTACCESSEDTIME { get; set; }
        public Nullable<System.DateTime> LASTCHANGEDPASSWORDTIME { get; set; }
        public Nullable<bool> TERMOFUSE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<long> CLIENTID { get; set; }
        public Nullable<int> PASSWORDSTATUS { get; set; }
        public Nullable<System.DateTime> ACTIVATIONDATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
    
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        public virtual USERLEVEL USERLEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASEANNOUNCEMENT> RELEASEANNOUNCEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASEINVOICE> RELEASEINVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE> ROLEs { get; set; }
    }
}
