//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINVOICE_DATA
    {
        public long ID { get; set; }
        public string MST { get; set; }
        public string XML { get; set; }
        public string MSTNT { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDBY { get; set; }
        public string MESSAGECODE { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string MCQT { get; set; }
        public string MLTDIEP { get; set; }
        public string TTXNCQT { get; set; }
        public string THOP { get; set; }
        public string LTBAO { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
    }
}
