//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYCOMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MYCOMPANY()
        {
            this.INVOICEs = new HashSet<INVOICE>();
            this.INVOICEDECLARATIONs = new HashSet<INVOICEDECLARATION>();
            this.INVOICERELEASES = new HashSet<INVOICERELEAS>();
            this.KEYSTOREs = new HashSet<KEYSTORE>();
            this.LOGINUSERs = new HashSet<LOGINUSER>();
            this.MYCOMPANY1 = new HashSet<MYCOMPANY>();
            this.NOTIFICATIONUSEINVOICEs = new HashSet<NOTIFICATIONUSEINVOICE>();
            this.NOTIFICATIONUSEINVOICEDETAILs = new HashSet<NOTIFICATIONUSEINVOICEDETAIL>();
            this.RELEASEANNOUNCEMENTs = new HashSet<RELEASEANNOUNCEMENT>();
            this.RELEASEINVOICEs = new HashSet<RELEASEINVOICE>();
            this.REPORTCANCELLINGs = new HashSet<REPORTCANCELLING>();
        }
    
        public long COMPANYSID { get; set; }
        public string COMPANYNAME { get; set; }
        public string TAXCODE { get; set; }
        public string ADDRESS { get; set; }
        public string TEL1 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string PERSONCONTACT { get; set; }
        public string DELEGATE { get; set; }
        public string BANKACCOUNT { get; set; }
        public string ACCOUNTHOLDER { get; set; }
        public string BANKNAME { get; set; }
        public Nullable<long> CITYID { get; set; }
        public Nullable<long> TAXDEPARTMENTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string LOGOFILENAME { get; set; }
        public string SIGNATUREFILENAME { get; set; }
        public string LEVELCUSTOMER { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string MOBILE { get; set; }
        public string POSITION { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<bool> OPENFILEWHENSIGN { get; set; }
        public Nullable<int> LEVELAGENCIES { get; set; }
        public string REPORTWEBSITE { get; set; }
        public string REPORTTEL { get; set; }
        public string EMAILOFCONTRACT { get; set; }
        public string NUMBERFORMAT { get; set; }
        public string CLIENTNUMBERFORMAT { get; set; }
        public Nullable<bool> VERIFICATIONTAX { get; set; }
        public Nullable<long> COREBRID { get; set; }
        public string BRANCHID { get; set; }
        public string COMPANYNAMEEN { get; set; }
        public string ADDRESSEN { get; set; }
    
        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICEDECLARATION> INVOICEDECLARATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICERELEAS> INVOICERELEASES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEYSTORE> KEYSTOREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGINUSER> LOGINUSERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MYCOMPANY> MYCOMPANY1 { get; set; }
        public virtual MYCOMPANY MYCOMPANY2 { get; set; }
        public virtual TAXDEPARTMENT TAXDEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATIONUSEINVOICE> NOTIFICATIONUSEINVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATIONUSEINVOICEDETAIL> NOTIFICATIONUSEINVOICEDETAILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASEANNOUNCEMENT> RELEASEANNOUNCEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASEINVOICE> RELEASEINVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTCANCELLING> REPORTCANCELLINGs { get; set; }
    }
}
