//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYCOMPANYUPGRADE
    {
        public decimal ID { get; set; }
        public long COMPANYSID { get; set; }
        public Nullable<long> TYPE { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<System.DateTime> APPLYDATE { get; set; }
        public string TAXCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS { get; set; }
        public string DELEGATE { get; set; }
        public string TEL { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
    }
}
