//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYCOMPANY_BK
    {
        public long COMPANYSID { get; set; }
        public string COMPANYNAME { get; set; }
        public string TAXCODE { get; set; }
        public string ADDRESS { get; set; }
        public string TEL1 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string PERSONCONTACT { get; set; }
        public string DELEGATE { get; set; }
        public string BANKACCOUNT { get; set; }
        public string ACCOUNTHOLDER { get; set; }
        public string BANKNAME { get; set; }
        public Nullable<long> CITYID { get; set; }
        public Nullable<long> TAXDEPARTMENTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string LOGOFILENAME { get; set; }
        public string SIGNATUREFILENAME { get; set; }
        public string LEVELCUSTOMER { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string MOBILE { get; set; }
        public string POSITION { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<bool> OPENFILEWHENSIGN { get; set; }
        public Nullable<int> LEVELAGENCIES { get; set; }
        public string REPORTWEBSITE { get; set; }
        public string REPORTTEL { get; set; }
        public string EMAILOFCONTRACT { get; set; }
        public string NUMBERFORMAT { get; set; }
        public string CLIENTNUMBERFORMAT { get; set; }
        public Nullable<bool> VERIFICATIONTAX { get; set; }
        public Nullable<long> COREBRID { get; set; }
        public string BRANCHID { get; set; }
        public string COMPANYNAMEEN { get; set; }
        public string ADDRESSEN { get; set; }
    }
}
