//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATIONUSEINVOICEDETAIL
    {
        public long ID { get; set; }
        public Nullable<long> NOTIFICATIONUSEINVOICEID { get; set; }
        public Nullable<long> REGISTERTEMPLATESID { get; set; }
        public string PREFIX { get; set; }
        public string SUFFIX { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> NUMBERUSE { get; set; }
        public string NUMBERFROM { get; set; }
        public string NUMBERTO { get; set; }
        public Nullable<System.DateTime> USEDDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<bool> ISRECEIVEDWARNING { get; set; }
        public string INVOICETYPENAME { get; set; }
        public string REGISTERTEMPLATECODE { get; set; }
        public string INVOICESAMPLENAME { get; set; }
        public Nullable<long> COMPANYID { get; set; }
    
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        public virtual NOTIFICATIONUSEINVOICE NOTIFICATIONUSEINVOICE { get; set; }
        public virtual REGISTERTEMPLATE REGISTERTEMPLATE { get; set; }
    }
}
