//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATIONMINVOICE
    {
        public long ID { get; set; }
        public Nullable<long> INVOICEID { get; set; }
        public string URL { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDBY { get; set; }
        public string MESSAGECODE { get; set; }
        public string NAME { get; set; }
    }
}
