//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATIONUSEINVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTIFICATIONUSEINVOICE()
        {
            this.NOTIFICATIONUSEINVOICEDETAILs = new HashSet<NOTIFICATIONUSEINVOICEDETAIL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public Nullable<long> TAXDEPARTMENTID { get; set; }
        public Nullable<long> CITYID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public string COMPANYNAME { get; set; }
        public string COMPANYADDRESS { get; set; }
        public string COMPANYTAXCODE { get; set; }
        public string COMPANYPHONE { get; set; }
        public string CITYNAME { get; set; }
        public string DELEGATE { get; set; }
        public string BANKACCOUNT { get; set; }
        public string TAXDEPARTMENTNAME { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        public virtual TAXDEPARTMENT TAXDEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATIONUSEINVOICEDETAIL> NOTIFICATIONUSEINVOICEDETAILs { get; set; }
    }
}
