//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUARZTJOB
    {
        public long ID { get; set; }
        public long JOBID { get; set; }
        public string SCHEDULENAME { get; set; }
        public string JOBNAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string SCRONEXPRESSION { get; set; }
        public Nullable<System.DateTime> NEXTTIMERUN { get; set; }
        public Nullable<System.DateTime> LASTTIMERUN { get; set; }
        public string WORKINGCALENDAR { get; set; }
        public Nullable<bool> PROCESSING { get; set; }
    
        public virtual JOB JOB { get; set; }
    }
}
