//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELEASEANNOUNCEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RELEASEANNOUNCEMENT()
        {
            this.RELEASEANNOUNCEMENTDETAILs = new HashSet<RELEASEANNOUNCEMENTDETAIL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> RELEASEDDATE { get; set; }
        public Nullable<long> RELEASEBY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string RELEASESTATUS { get; set; }
    
        public virtual LOGINUSER LOGINUSER { get; set; }
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELEASEANNOUNCEMENTDETAIL> RELEASEANNOUNCEMENTDETAILs { get; set; }
    }
}
