//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELEASEINVOICEDETAIL
    {
        public long ID { get; set; }
        public Nullable<long> RELEASEINVOICEID { get; set; }
        public Nullable<long> INVOICEID { get; set; }
        public string VERIFICATIONCODE { get; set; }
        public Nullable<bool> SENDFORCUSTOMER { get; set; }
        public Nullable<int> PROCESSSTATUS { get; set; }
        public Nullable<int> CUSTOMERVERIFIED { get; set; }
        public Nullable<int> SENDEMAILSTATUS { get; set; }
        public string MESSAGES { get; set; }
        public Nullable<bool> SIGNED { get; set; }
        public Nullable<bool> PRINTED { get; set; }
        public Nullable<bool> CONVERTED { get; set; }
        public Nullable<System.DateTime> CONVERTDATE { get; set; }
        public string CONVERTER { get; set; }
    
        public virtual RELEASEINVOICE RELEASEINVOICE { get; set; }
    }
}
