//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTCANCELLINGDETAIL
    {
        public long ID { get; set; }
        public Nullable<long> REPORTCANCELLINGID { get; set; }
        public Nullable<long> REGISTERTEMPLATESID { get; set; }
        public string CODE { get; set; }
        public string SYMBOL { get; set; }
        public string NUMBERFROM { get; set; }
        public string NUMBERTO { get; set; }
        public Nullable<decimal> NUMBER { get; set; }
    
        public virtual REGISTERTEMPLATE REGISTERTEMPLATE { get; set; }
        public virtual REPORTCANCELLING REPORTCANCELLING { get; set; }
    }
}
