//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTCANCELLING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTCANCELLING()
        {
            this.REPORTCANCELLINGDETAILs = new HashSet<REPORTCANCELLINGDETAIL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string TYPECANCELLING { get; set; }
        public Nullable<int> HOURCANCELLING { get; set; }
        public Nullable<int> MINUTECANCELLING { get; set; }
        public Nullable<System.DateTime> CANCELLINGDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string DELEGATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<long> APPROVEDBY { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
    
        public virtual MYCOMPANY MYCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTCANCELLINGDETAIL> REPORTCANCELLINGDETAILs { get; set; }
    }
}
