//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEFUNCTION
    {
        public long ID { get; set; }
        public long ROLEID { get; set; }
        public long FUNCTIONID { get; set; }
        public string ACTION { get; set; }
    
        public virtual FUNCTION FUNCTION { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
