//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQUENCE_CONFIG
    {
        public string IYEAR { get; set; }
        public decimal COMPANYID { get; set; }
        public string SYMBOL { get; set; }
        public string SEQ_NAME { get; set; }
    }
}
