//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNATURE
    {
        public long ID { get; set; }
        public long COMPANYID { get; set; }
        public string SERIALNUMBER { get; set; }
        public string COMPANYNAME { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> TYPESIGN { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<int> SLOTS { get; set; }
        public string FILENAME { get; set; }
        public string IPADDRESS { get; set; }
        public string PASSWORDCA { get; set; }
        public string RELEASENAME { get; set; }
        public string CERTSERIALNUMBER { get; set; }
    }
}
