//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNDETAIL
    {
        public long ID { get; set; }
        public Nullable<long> INVOICEID { get; set; }
        public string SERIALNUMBER { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> ISCLIENTSIGN { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> ANNOUNCEMENTID { get; set; }
        public Nullable<int> TYPESIGN { get; set; }
    }
}
