//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTICAL
    {
        public long ID { get; set; }
        public long INVOICEID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> AMOUNTTAX { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TRADDATE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> EXCHANGERATE { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
    }
}
