//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMBOL
    {
        public long ID { get; set; }
        public Nullable<long> REFID { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string SYMBOL1 { get; set; }
    
        public virtual INVOICEDECLARATION INVOICEDECLARATION { get; set; }
    }
}
