//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMLOG
    {
        public long ID { get; set; }
        public string FUNCTIONCODE { get; set; }
        public string LOGSUMMARY { get; set; }
        public Nullable<decimal> LOGTYPE { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string LOGDETAIL { get; set; }
        public string IP { get; set; }
        public string USERNAME { get; set; }
    }
}
