//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMSETTING
    {
        public long ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> RATIO { get; set; }
        public Nullable<int> EXCHANGERATE { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<int> CONVERTEDAMOUNT { get; set; }
        public Nullable<int> NUMBERS { get; set; }
        public Nullable<int> STEPTOCREATEINVOICENO { get; set; }
        public Nullable<bool> SIGNAFTERAPPROVE { get; set; }
        public Nullable<bool> SERVERSIGN { get; set; }
        public Nullable<int> ROWNUMBER { get; set; }
        public Nullable<bool> ISWARNINGMINIMUM { get; set; }
        public string EMAILRECEIVEWARNING { get; set; }
        public Nullable<int> NUMBERMINIMUM { get; set; }
    }
}
