//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServer.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_GETFUNCTIONOFUSER
    {
        public long USERSID { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<long> COMPANYID { get; set; }
        public string FUNCTIONNAME { get; set; }
        public string DETAILFUNCTION { get; set; }
        public string ACTION { get; set; }
        public Nullable<int> ORDERS { get; set; }
        public long ROLEFUNCTIONID { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
